version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - "$PWD/db_data:/var/lib/mysql"
       - "$PWD/sqls:/tmp/sqls"
     restart: "no"
     ports:
       - "33306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - "$PWD/wordpress:/var/www/html"
     ports:
       - "8300:80"
     restart: "no"
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress


